### ISSUE TITLE
[Enhancement]: Dark Mode needed

### ISSUE THREAD

**Issue by Speedevs** [scroll-tech/scroll-documentation#167]
### What would you like us to improve?

No dark mode when your bridging from Ethereum to Base.

Community needs dark mode , especially when your bridging in late night 

### How important it is?

Very important to add Dark mode to the  official bridge 
https://scroll.io/bridge

**Comment by dghelm** [comment]
Thanks for the suggestion -- added to the documentation and passed along to frontend team who work on the bridge in the @scroll-tech/scroll-frontends repo.
