### ISSUE TITLE
 Bridging Assets to Scroll: A Beginner's Guide

### ISSUE THREAD

**Issue by Traicye** [scroll-tech/scroll-documentation#176]
### What would you like us to add?

Introduction:

Scroll is a Layer 2 scaling solution for Ethereum, offering faster and cheaper transactions. However, moving funds between Scroll and other blockchains like Ethereum requires bridging, often leaving users confused about the process. This guide will explain different bridging options for beginners, focusing on security and ease of use.

Prerequisites:

A MetaMask wallet (or similar) with some ETH for gas fees.
Basic understanding of crypto wallets and blockchain terminology.
Bridging options:

1. Ren Protocol:

Pros: Widely used, integrates seamlessly with MetaMask, supports bridging various assets.
Cons: Higher fees compared to other options.

Steps:
Visit https://renprotocol.org/ and connect your MetaMask wallet.
Select the assets you want to bridge (e.g., ETH, USDC) and input the desired amount.
Choose "Scroll L2" as the destination network.
Review the transaction details and confirm.

2. Rainbow Bridge:

Pros: user-friendly interface, relatively low fees compared to Ren.
Cons: Limited asset support currently (primarily ETH and stablecoins).
Steps:

Visit [https://en.wikipedia.org/wiki/Rainbow_Bridge_%28pets%29](https://en.wikipedia.org/wiki/Rainbow_Bridge_(pets)) and connect your MetaMask wallet.
Select the asset and amount you want to bridge.
Choose "Scroll L2" as the destination network.
Follow the on-screen instructions to confirm the transaction.
3. Orbiter Finance:

Pros: highly secure, permissionless bridge architecture.
Cons: Requires understanding of decentralized governance and voting for bridge parameters.

Steps:
Visit https://www.orbiter.finance/ and connect your MetaMask wallet.
Select the asset and amount you want to bridge.
Choose "Scroll L2" as the destination network.
Review the voting process and transaction details before confirming.

Remember:
Always double-check the network selection before bridging.
Consider transaction fees and bridge security before choosing an option.
Start with small amounts for testing before bridging larger sums.

Additional Resources:
Scroll Documentation: https://docs.scroll.io/en/developers/
Ren Protocol Docs: https://docs.renproject.io/ren/
Rainbow Bridge Docs: https://rainbowbridge.app/
Orbiter Finance Docs: https://orbiter-finance.medium.com/

### How important it is?

Reasons for its importance:

Addresses a key user need: Bridging assets is a crucial step for users transitioning between Scroll and other blockchains. A clear and concise guide like mine simplifies this process, fostering wider adoption and user confidence.

Focuses on a beginner-friendly approach: Many users new to Scroll might find bridging intimidating. My tutorial caters to that audience, making the ecosystem more accessible and welcoming.

Highlights various bridging options: Providing an overview of different bridges empowers users to compare their features, fees, and security aspects before choosing the most suitable option.

Integrates with official resources: Linking to relevant documentation adds credibility and helps users delve deeper into specific bridges if needed.

Overall, my contribution addresses a practical need, educates users, and promotes informed participation in the Scroll ecosystem. While its impact can't be definitively quantified, it undoubtedly fills a valuable gap and empowers users within the growing Scroll community.

**Comment by estheroche** [comment]
i can take this, kindly assign this to me

**Comment by dghelm** [comment]
This is a great guide, and I encourage you to publish it on another channel. However the technical documentation is not the place to be endorsing specific bridges or protocols. We hope to have a place in the documentation for community-contributed guides soon.
