### ISSUE TITLE
[Translate]: scroll-documentation/public/locales/

### ISSUE THREAD

**Issue by Phipsik** [scroll-tech/scroll-documentation#178]
### What would you like us to improve?

Translate to russian language. 
I have translated "rpc-table-component" into Russian, you can review the changes in the fork:

Please include the changes with the title, so that I can make changes and your repository (https://github.com/Phipsik/scroll-documentation/blob/develop/public/locales/ru/translation.json), thank you.

### How important it is?

The translation into the Russian language is seen as very important due to the large number of users from Russia.

**Comment by dghelm** [comment]
Thanks for the contribution! Currently, we require translations for any new language to be of the entire repo and work with contributors to do this. If you or an Ethereum community of Russian speakers are interested in taking this on, please reach out in a new issue mentioning the community or relevant skills/experience.
