### ISSUE TITLE
UI/UX not properly arranged on Scroll.io documentation page

### ISSUE THREAD

**Issue by monarch619** [scroll-tech/scroll-documentation#179]
### What would you like us to add?

The user interface should be structured in a way that facilitates seamless navigation.

### How important it is?

The importance of having a properly arranged UI for easy navigation cannot be overstated. A well-structured and intuitive user interface allows users to navigate through a website or application with minimal effort, enhancing the overall user experience.

**Comment by monarch619** [comment]
Consistent Design
Clear Labels
Prioritize Important Links
Visual Indicators

**Comment by dghelm** [comment]
Thanks for the review, but if you have specific items that don't meet your standards for the UI, please include screenshots and specifics and I can pass them along to our design team. That said, I think the docs look pretty good!
