### ISSUE TITLE
Add swap feature to testnet home page

### ISSUE THREAD

**Issue by JideijeEmeka** [scroll-tech/scroll-documentation#186]
### What would you like us to improve?

Adding a swap feature to the frontend testnet page would be of great improvement just as the bridge is present too.

### How important it is?

Its very important as swapping goes together with bridging

**Comment by dghelm** [comment]
Although we have made https://uniswap-showcase.sepolia.scroll.xyz/#/swap available, we do not want to endorse any specific dex project. Please see our Ecosystem page for lots of great DeFi projects on our testnet.
