### ISSUE TITLE
RPC ISSUE

### ISSUE THREAD

**Issue by monarch619** [scroll-tech/scroll-documentation#189]
### Describe the bug

╔═══════════════════╗
║ TRANSACTION ERROR ║
╚═══════════════════╝

Reason: Internal JSON-RPC error.

╔═════════════════════════╗
║ TRANSACTION INFORMATION ║
╚═════════════════════════╝

from:      0x7e7bFEa0D4Be46cF28a5f19BE902D853dF85fDb4
chain:     unknown (534352)
rpc:       534352.rpc.thirdweb.com
data:      0x6101006040527f6e71edae12b1b97f4d1f60370fef10105fa2faae0126114a169c64845d6126c960e0523480156200003657600080fd5b5060405162002c4838038062002c488339810160408190526200005991620003f5565b8282828181818181600590805190602001906200007892919062000265565b5080516200008e90600690602084019062000265565b50504660a052503060c052620000a3620000e2565b60805250620000b490508362000179565b5050600880546001600160a01b0319166001600160a01b03969096169590951790945550620004c292505050565b60007f8b73c3c69bb8fe3d512ecc4cf759cc79239f7b179b0ffacaa9a75d522b39400f6200010f620001cb565b80516020918201206040805192830193909352918101919091527fc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc660608201524660808201523060a082015260c00160405160208183030381529060405280519060200120905090565b600180546001600160a01b038381166001600160a01b0319831681179093556040519116919082907f8292fce18fa69edf4db7b94ea2e58241df0ae57f97e0a6c9b29067028bf92d7690600090a35050565b606060058054620001dc9062000485565b80601f01602080910402602001604051908101604052809291908181526020018280546200020a9062000485565b80156200025b5780601f106200022f576101008083540402835291602001916200025b565b820191906000526020600020905b8154815290600101906020018083116200023d57829003601f168201915b5050505050905090565b828054620002739062000485565b90600052602060002090601f016020900481019282620002975760008555620002e2565b82601f10620002b257805160ff1916838001178555620002e2565b82800160010185558215620002e2579182015b82811115620002e2578251825591602001919060010190620002c5565b50620002f0929150620002f4565b5090565b5b80821115620002f05760008155600101620002f5565b80516001600160a01b03811681146200032357600080fd5b919050565b634e487b7160e01b600052604160045260246000fd5b600082601f8301126200035057600080fd5b81516001600160401b03808211156200036d576200036d62000328565b604051601f8301601f19908116603f0116810190828211818310171562000398576200039862000328565b81604052838152602092508683858801011115620003b557600080fd5b600091505b83821015620003d95785820183015181830184015290820190620003ba565b83821115620003eb5760008385830101525b9695505050505050565b600080600080608085870312156200040c57600080fd5b62000417856200030b565b935062000427602086016200030b565b60408601519093506001600160401b03808211156200044557600080fd5b62000453888389016200033e565b935060608701519150808211156200046a57600080fd5b5062000479878288016200033e565b91505092959194509250565b600181811c908216806200049a57607f821691505b60208210811415620004bc57634e487b7160e01b600052602260045260246000fd5b50919050565b60805160a05160c05160e05161274c620004fc600039600061139e015260006107ec0152600061081601526000610840015261274c6000f3fe6080604052600436106101c25760003560e01c80637386479e116100f7578063a457c2d711610095578063d505accf11610064578063d505accf14610519578063dd62ed3e14610539578063e8a3d48514610559578063fc0c546a1461056e57600080fd5b8063a457c2d71461048c578063a9059cbb146104ac578063ac9650d8146104cc578063c722ecc4146104f957600080fd5b80638da5cb5b116100d15780638da5cb5b146103f0578063938e3d7b1461042257806395d89b41146104425780639c8f9f231461045757600080fd5b80637386479e1461037a57806379cc67901461039a5780637ecebe00146103ba57600080fd5b80633644e5151161016457806342966c681161013e57806342966c68146102f1578063449a52f81461031157806351c6590a1461033157806370a082311461034457600080fd5b80633644e515146102a757806339509351146102bc5780633c2f1806146102dc57600080fd5b806318160ddd116101a057806318160ddd1461024457806323b872dd14610263578063313ce567146102835780633575745d1461029f57600080fd5b806306fdde03146101c7578063095ea7b3146101f257806313af403514610222575b600080fd5b3480156101d357600080fd5b506101dc61058e565b6040516101e991906121a5565b60405180910390f35b3480156101fe57600080fd5b5061021261020d3660046121d4565b610620565b60405190151581526020016101e9565b34801561022e57600080fd5b5061024261023d3660046121fe565b610638565b005b34801561025057600080fd5b506004545b6040519081526020016101e9565b34801561026f57600080fd5b5061021261027e366004612219565b61068e565b34801561028f57600080fd5b50604051601281526020016101e9565b6102426106b2565b3480156102b357600080fd5b506102556107df565b3480156102c857600080fd5b506102126102d73660046121d4565b61086f565b3480156102e857600080fd5b506102556108ae565b3480156102fd57600080fd5b5061024261030c366004612255565b61092a565b34801561031d57600080fd5b5061024261032c3660046121d4565b610988565b61025561033f366004612255565b610a2e565b34801561035057600080fd5b5061025561035f3660046121fe565b6001600160a01b031660009081526002602052604090205490565b34801561038657600080fd5b5061025561039536600461226e565b610c89565b3480156103a657600080fd5b506102426103b53660046121d4565b610d1d565b3480156103c657600080fd5b506102556103d53660046121fe565b6001600160a01b031660009081526007602052604090205490565b3480156103fc57600080fd5b506001546001600160a01b03165b6040516001600160a01b0390911681526020016101e9565b34801561042e57600080fd5b5061024261043d3660046122b0565b610e0e565b34801561044e57600080fd5b506101dc610e5c565b34801561046357600080fd5b50610477610472366004612255565b610e6b565b604080519283526020830191909152016101e9565b34801561049857600080fd5b506102126104a73660046121d4565b610fd8565b3480156104b857600080fd5b506102126104c73660046121d4565b61106a565b3480156104d857600080fd5b506104ec6104e7366004612361565b611078565b6040516101e991906123d6565b34801561050557600080fd5b50610242610514366004612255565b6111e8565b34801561052557600080fd5b50610242610534366004612438565b61134a565b34801561054557600080fd5b506102556105543660046124ab565b6114d0565b34801561056557600080fd5b506101dc6114fb565b34801561057a57600080fd5b5060085461040a906001600160a01b031681565b60606005805461059d906124de565b80601f01602080910402602001604051908101604052809291908181526020018280546105c9906124de565b80156106165780601f106105eb57610100808354040283529160200191610616565b820191906000526020600020905b8154815290600101906020018083116105f957829003601f168201915b5050505050905090565b60003361062e818585611589565b5060019392505050565b6106406116ad565b6106825760405162461bcd60e51b815260206004820152600e60248201526d139bdd08185d5d1a1bdc9a5e995960921b60448201526064015b60405180910390fd5b61068b816116da565b50565b60003361069c85828561172c565b6106a78585856117a0565b506001949350505050565b600034116106f35760405162461bcd60e51b815260206004820152600e60248201526d04e6f2045544820746f20737761760941b6044820152606401610679565b60006106fd6108ae565b9050600061070c344784610c89565b9050600081116107565760405162461bcd60e51b81526020600482015260156024820152742737903a37b5b2b739903a37903a3930b739b332b960591b6044820152606401610679565b60085460405163a9059cbb60e01b8152336004820152602481018390526001600160a01b039091169063a9059cbb90604401602060405180830381600087803b1580156107a257600080fd5b505af11580156107b6573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906107da9190612513565b505050565b6000306001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001614801561083857507f000000000000000000000000000000000000000000000000000000000000000046145b1561086257507f000000000000000000000000000000000000000000000000000000000000000090565b61086a61196e565b905090565b3360008181526003602090815260408083206001600160a01b038716845290915281205490919061062e90829086906108a990879061254b565b611589565b6008546040516370a0823160e01b81523060048201526000916001600160a01b0316906370a082319060240160206040518083038186803b1580156108f257600080fd5b505afa158015610906573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061086a9190612563565b3360009081526002602052604090205481111561097e5760405162461bcd60e51b81526020600482015260126024820152716e6f7420656e6f7567682062616c616e636560701b6044820152606401610679565b61068b3382611a03565b6109906116ad565b6109dc5760405162461bcd60e51b815260206004820152601760248201527f4e6f7420617574686f72697a656420746f206d696e742e0000000000000000006044820152606401610679565b80610a205760405162461bcd60e51b815260206004820152601460248201527326b4b73a34b733903d32b937903a37b5b2b7399760611b6044820152606401610679565b610a2a8282611b51565b5050565b6000808211610a7f5760405162461bcd60e51b815260206004820181905260248201527f416d6f756e74206d7573742062652067726561746572207468616e207a65726f6044820152606401610679565b60004781610a8b6108ae565b6008549091506001600160a01b031681610b38576040516323b872dd60e01b8152336004820152306024820152604481018790526001600160a01b038216906323b872dd90606401602060405180830381600087803b158015610aed57600080fd5b505af1158015610b01573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610b259190612513565b50829350610b333387611b51565b610c7f565b6000610b44348561257c565b905080610b518434612593565b610b5b91906125c8565b871015610bd05760405162461bcd60e51b815260206004820152603e60248201527f416d6f756e74206f6620746f6b656e732073656e74206973206c65737320746860448201527f616e20746865206d696e696d756d20746f6b656e7320726571756972656400006064820152608401610679565b6040516323b872dd60e01b8152336004820152306024820152604481018890526001600160a01b038316906323b872dd90606401602060405180830381600087803b158015610c1e57600080fd5b505af1158015610c32573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610c569190612513565b508034610c6260045490565b0281610c7057610c706125b2565b049450610c7d3386611b51565b505b5091949350505050565b60008083118015610c9a5750600082115b610cd95760405162461bcd60e51b815260206004820152601060248201526f496e76616c696420526573657276657360801b6044820152606401610679565b836000610ce68483612593565b9050600082610cf6876064612593565b610d00919061254b565b9050808281610d1157610d116125b2565b04979650505050505050565b610d256116ad565b610d715760405162461bcd60e51b815260206004820152601760248201527f4e6f7420617574686f72697a656420746f206275726e2e0000000000000000006044820152606401610679565b80610d91836001600160a01b031660009081526002602052604090205490565b1015610dd45760405162461bcd60e51b81526020600482015260126024820152716e6f7420656e6f7567682062616c616e636560701b6044820152606401610679565b600081610de184336114d0565b610deb919061257c565b9050610df983336000611589565b610e04833383611589565b6107da8383611a03565b610e166116ad565b610e535760405162461bcd60e51b815260206004820152600e60248201526d139bdd08185d5d1a1bdc9a5e995960921b6044820152606401610679565b61068b81611c30565b60606006805461059d906124de565b60008060008311610ebe5760405162461bcd60e51b815260206004820181905260248201527f416d6f756e74206d7573742062652067726561746572207468616e207a65726f6044820152606401610679565b476000610eca60045490565b90506000610ed760045490565b610ee18785612593565b610eeb91906125c8565b905060008287610ef96108ae565b610f039190612593565b610f0d91906125c8565b9050610f193388611a03565b604051339083156108fc029084906000818181858888f19350505050158015610f46573d6000803e3d6000fd5b5060085460405163a9059cbb60e01b8152336004820152602481018390526001600160a01b039091169063a9059cbb90604401602060405180830381600087803b158015610f9357600080fd5b505af1158015610fa7573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610fcb9190612513565b5090969095509350505050565b3360008181526003602090815260408083206001600160a01b03871684529091528120549091908381101561105d5760405162461bcd60e51b815260206004820152602560248201527f45524332303a2064656372656173656420616c6c6f77616e63652062656c6f77604482015264207a65726f60d81b6064820152608401610679565b6106a78286868403611589565b60003361062e8185856117a0565b60608167ffffffffffffffff8111156110935761109361229a565b6040519080825280602002602001820160405280156110c657816020015b60608152602001906001900390816110b15790505b509050336000805b848110156111df57811561114d5761112b308787848181106110f2576110f26125ea565b90506020028101906111049190612600565b866040516020016111179392919061264e565b604051602081830303815290604052611d11565b84828151811061113d5761113d6125ea565b60200260200101819052506111cd565b6111af30878784818110611163576111636125ea565b90506020028101906111759190612600565b8080601f016020809104026020016040519081016040528093929190818152602001838380828437600092019190915250611d1192505050565b8482815181106111c1576111c16125ea565b60200260200101819052505b806111d781612674565b9150506110ce565b50505092915050565b6000811161122c5760405162461bcd60e51b815260206004820152601160248201527004e6f20746f6b656e7320746f207377617607c1b6044820152606401610679565b60006112366108ae565b90506000611245838347610c89565b90506000811161128c5760405162461bcd60e51b815260206004820152601260248201527127379022aa24103a37903a3930b739b332b960711b6044820152606401610679565b6008546040516323b872dd60e01b8152336004820152306024820152604481018590526001600160a01b03909116906323b872dd90606401602060405180830381600087803b1580156112de57600080fd5b505af11580156112f2573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906113169190612513565b50604051339082156108fc029083906000818181858888f19350505050158015611344573d6000803e3d6000fd5b50505050565b8342111561139a5760405162461bcd60e51b815260206004820152601d60248201527f45524332305065726d69743a206578706972656420646561646c696e650000006044820152606401610679565b60007f00000000000000000000000000000000000000000000000000000000000000008888886113c98c611d3d565b6040805160208101969096526001600160a01b0394851690860152929091166060840152608083015260a082015260c0810186905260e00160405160208183030381529060405280519060200120905060006114466114266107df565b8360405161190160f01b8152600281019290925260228201526042902090565b9050600061145682878787611d65565b9050896001600160a01b0316816001600160a01b0316146114b95760405162461bcd60e51b815260206004820152601e60248201527f45524332305065726d69743a20696e76616c6964207369676e617475726500006044820152606401610679565b6114c48a8a8a611589565b50505050505050505050565b6001600160a01b03918216600090815260036020908152604080832093909416825291909152205490565b60008054611508906124de565b80601f0160208091040260200160405190810160405280929190818152602001828054611534906124de565b80156115815780601f1061155657610100808354040283529160200191611581565b820191906000526020600020905b81548152906001019060200180831161156457829003601f168201915b505050505081565b6001600160a01b0383166115eb5760405162461bcd60e51b8152602060048201526024808201527f45524332303a20617070726f76652066726f6d20746865207a65726f206164646044820152637265737360e01b6064820152608401610679565b6001600160a01b03821661164c5760405162461bcd60e51b815260206004820152602260248201527f45524332303a20617070726f766520746f20746865207a65726f206164647265604482015261737360f01b6064820152608401610679565b6001600160a01b0383811660008181526003602090815260408083209487168084529482529182902085905590518481527f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925910160405180910390a3505050565b60006116c16001546001600160a01b031690565b6001600160a01b0316336001600160a01b031614905090565b600180546001600160a01b038381166001600160a01b0319831681179093556040519116919082907f8292fce18fa69edf4db7b94ea2e58241df0ae57f97e0a6c9b29067028bf92d7690600090a35050565b600061173884846114d0565b9050600019811461134457818110156117935760405162461bcd60e51b815260206004820152601d60248201527f45524332303a20696e73756666696369656e7420616c6c6f77616e63650000006044820152606401610679565b6113448484848403611589565b6001600160a01b0383166118045760405162461bcd60e51b815260206004820152602560248201527f45524332303a207472616e736665722066726f6d20746865207a65726f206164604482015264647265737360d81b6064820152608401610679565b6001600160a01b0382166118665760405162461bcd60e51b815260206004820152602360248201527f45524332303a207472616e7366657220746f20746865207a65726f206164647260448201526265737360e81b6064820152608401610679565b6001600160a01b038316600090815260026020526040902054818110156118de5760405162461bcd60e51b815260206004820152602660248201527f45524332303a207472616e7366657220616d6f756e7420657863656564732062604482015265616c616e636560d01b6064820152608401610679565b6001600160a01b0380851660009081526002602052604080822085850390559185168152908120805484929061191590849061254b565b92505081905550826001600160a01b0316846001600160a01b03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef8460405161196191815260200190565b60405180910390a3611344565b60007f8b73c3c69bb8fe3d512ecc4cf759cc79239f7b179b0ffacaa9a75d522b39400f61199961058e565b80516020918201206040805192830193909352918101919091527fc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc660608201524660808201523060a082015260c00160405160208183030381529060405280519060200120905090565b6001600160a01b038216611a635760405162461bcd60e51b815260206004820152602160248201527f45524332303a206275726e2066726f6d20746865207a65726f206164647265736044820152607360f81b6064820152608401610679565b6001600160a01b03821660009081526002602052604090205481811015611ad75760405162461bcd60e51b815260206004820152602260248201527f45524332303a206275726e20616d6f756e7420657863656564732062616c616e604482015261636560f01b6064820152608401610679565b6001600160a01b0383166000908152600260205260408120838303905560048054849290611b0690849061257c565b90915550506040518281526000906001600160a01b038516907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a3505050565b6001600160a01b038216611ba75760405162461bcd60e51b815260206004820152601f60248201527f45524332303a206d696e7420746f20746865207a65726f2061646472657373006044820152606401610679565b8060046000828254611bb9919061254b565b90915550506001600160a01b03821660009081526002602052604081208054839290611be690849061254b565b90915550506040518181526001600160a01b038316906000907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a35050565b6000808054611c3e906124de565b80601f0160208091040260200160405190810160405280929190818152602001828054611c6a906124de565b8015611cb75780601f10611c8c57610100808354040283529160200191611cb7565b820191906000526020600020905b815481529060010190602001808311611c9a57829003601f168201915b50508551939450611cd3936000935060208701925090506120b4565b507fc9c7c3fe08b88b4df9d4d47ef47d2c43d55c025a0ba88ca442580ed9e7348a168183604051611d0592919061268f565b60405180910390a15050565b6060611d3683836040518060600160405280602781526020016126f060279139611d8f565b9392505050565b6001600160a01b03811660009081526007602052604090208054600181018255905b50919050565b6000806000611d7687878787611e07565b91509150611d8381611ecb565b5090505b949350505050565b6060600080856001600160a01b031685604051611dac91906126bd565b600060405180830381855af49150503d8060008114611de7576040519150601f19603f3d011682016040523d82523d6000602084013e611dec565b606091505b5091509150611dfd86838387612019565b9695505050505050565b6000807f7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0831115611e3e5750600090506003611ec2565b6040805160008082526020820180845289905260ff881692820192909252606081018690526080810185905260019060a0016020604051602081039080840390855afa158015611e92573d6000803e3d6000fd5b5050604051601f1901519150506001600160a01b038116611ebb57600060019250925050611ec2565b9150600090505b94509492505050565b6000816004811115611edf57611edf6126d9565b1415611ee85750565b6001816004811115611efc57611efc6126d9565b1415611f4a5760405162461bcd60e51b815260206004820152601860248201527f45434453413a20696e76616c6964207369676e617475726500000000000000006044820152606401610679565b6002816004811115611f5e57611f5e6126d9565b1415611fac5760405162461bcd60e51b815260206004820152601f60248201527f45434453413a20696e76616c6964207369676e6174757265206c656e677468006044820152606401610679565b6003816004811115611fc057611fc06126d9565b141561068b5760405162461bcd60e51b815260206004820152602260248201527f45434453413a20696e76616c6964207369676e6174757265202773272076616c604482015261756560f01b6064820152608401610679565b6060831561208557825161207e576001600160a01b0385163b61207e5760405162461bcd60e51b815260206004820152601d60248201527f416464726573733a2063616c6c20746f206e6f6e2d636f6e74726163740000006044820152606401610679565b5081611d87565b611d87838381511561209a5781518083602001fd5b8060405162461bcd60e51b815260040161067991906121a5565b8280546120c0906124de565b90600052602060002090601f0160209004810192826120e25760008555612128565b82601f106120fb57805160ff1916838001178555612128565b82800160010185558215612128579182015b8281111561212857825182559160200191906001019061210d565b50612134929150612138565b5090565b5b808211156121345760008155600101612139565b60005b83811015612168578181015183820152602001612150565b838111156113445750506000910152565b6000815180845261219181602086016020860161214d565b601f01601f19169290920160200192915050565b602081526000611d366020830184612179565b80356001600160a01b03811681146121cf57600080fd5b919050565b600080604083850312156121e757600080fd5b6121f0836121b8565b946020939093013593505050565b60006020828403121561221057600080fd5b611d36826121b8565b60008060006060848603121561222e57600080fd5b612237846121b8565b9250612245602085016121b8565b9150604084013590509250925092565b60006020828403121561226757600080fd5b5035919050565b60008060006060848603121561228357600080fd5b505081359360208301359350604090920135919050565b634e487b7160e01b600052604160045260246000fd5b6000602082840312156122c257600080fd5b813567ffffffffffffffff808211156122da57600080fd5b818401915084601f8301126122ee57600080fd5b8135818111156123005761230061229a565b604051601f8201601f19908116603f011681019083821181831017156123285761232861229a565b8160405282815287602084870101111561234157600080fd5b826020860160208301376000928101602001929092525095945050505050565b6000806020838503121561237457600080fd5b823567ffffffffffffffff8082111561238c57600080fd5b818501915085601f8301126123a057600080fd5b8135818111156123af57600080fd5b8660208260051b85010111156123c457600080fd5b60209290920196919550909350505050565b6000602080830181845280855180835260408601915060408160051b870101925083870160005b8281101561242b57603f19888603018452612419858351612179565b945092850192908501906001016123fd565b5092979650505050505050565b600080600080600080600060e0888a03121561245357600080fd5b61245c886121b8565b965061246a602089016121b8565b95506040880135945060608801359350608088013560ff8116811461248e57600080fd5b9699959850939692959460a0840135945060c09093013592915050565b600080604083850312156124be57600080fd5b6124c7836121b8565b91506124d5602084016121b8565b90509250929050565b600181811c908216806124f257607f821691505b60208210811415611d5f57634e487b7160e01b600052602260045260246000fd5b60006020828403121561252557600080fd5b81518015158114611d3657600080fd5b634e487b7160e01b600052601160045260246000fd5b6000821982111561255e5761255e612535565b500190565b60006020828403121561257557600080fd5b5051919050565b60008282101561258e5761258e612535565b500390565b60008160001904831182151516156125ad576125ad612535565b500290565b634e487b7160e01b600052601260045260246000fd5b6000826125e557634e487b7160e01b600052601260045260246000fd5b500490565b634e487b7160e01b600052603260045260246000fd5b6000808335601e1984360301811261261757600080fd5b83018035915067ffffffffffffffff82111561263257600080fd5b60200191503681900382131561264757600080fd5b9250929050565b8284823760609190911b6bffffffffffffffffffffffff19169101908152601401919050565b600060001982141561268857612688612535565b5060010190565b6040815260006126a26040830185612179565b82810360208401526126b48185612179565b95945050505050565b600082516126cf81846020870161214d565b9190910192915050565b634e487b7160e01b600052602160045260246000fdfe416464726573733a206c6f772d6c6576656c2064656c65676174652063616c6c206661696c6564a26469706673582212204d6af1d994bca7585fc1bda6b2fa552246ca546bd404482bf296dce998c867c464736f6c6343000809003300000000000000000000000071c5abe6a74a82bfda07239113c533e414ac830e0000000000000000000000007e7bfea0d4be46cf28a5f19be902d853df85fdb4000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000c444558204c5020546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000054445584c50000000000000000000000000000000000000000000000000000000
method:

  deployContract(
    "0x71C5Abe6A74a82BFDa07239113c533e414Ac830E",
    "0x7e7bFEa0D4Be46cF28a5f19BE902D853dF85fDb4",
    "DEX LP Token",
    "DEXLP"
  )

there is error in chain id
![photo_2024-02-24_12-35-46](https://github.com/scroll-tech/scroll-documentation/assets/64332966/2b63640a-efd7-4681-9f42-079d5bb5c6cb)

### To Reproduce

each time i try to bridge or deploy a contract its shows RPC error

### URLs

- https://docs.scroll.io/..
- ...

### Expected behavior

[
![photo_2024-02-24_12-35-46](https://github.com/scroll-tech/scroll-documentation/assets/64332966/aefa17a9-22d2-48c5-8a67-e04eaa8a140d)

**Comment by dghelm** [comment]
Not the right place for chain support. Please join our discord, reach out to thirdweb about their RPC or discuss this with the application developer.
