### ISSUE TITLE
[Enhancement]: Docs increased readability and clarity

### ISSUE THREAD

**Issue by elsaicequeen** [scroll-tech/scroll-documentation#193]
### What would you like us to improve?

To enhance the readability and clarity of the "Contributing to the Scroll Documentation" guide, consider the following revisions. The aim is to make instructions more detailed and helpful for contributors, especially those who might be contributing for the first time.
Added to this branch here.
https://github.com/elsaicequeen/scroll-documentation

### How important it is?

Helpful for beginners and new contributors. Low importance.

**Comment by dghelm** [comment]
If you want to discuss items raised in the PR and work out specific templates, please raise another issue and the team can discuss, but anything process based should be worked out before raising a PR.
