### ISSUE TITLE
INTEGRATING P2E INTO SCROLL.

### ISSUE THREAD

**Issue by hoyeen17** [scroll-tech/scroll-documentation#201]
### What would you like us to add?

Adding a game to the project would be nice where every challenges and power ups are written in a scroll. I got this idea from the Animation 'Kung 
![Uploading af5472239c62224335151bdf5391e43f.jpg…]()
Fu Panda' where he was given a SCROLL as the new Dragon Warrior and as we all know, it is the Dragon year.

### How important it is?

With the hype around Gamefi projects in the space, I feel it would be nice having one P2E in this project where NFTs can be used as a reward and also serve as a key to future rewards.

**Comment by dghelm** [comment]
Outside the scope of this repo.
