### ISSUE TITLE
[Bug]: eth_call return error 

### ISSUE THREAD

**Issue by cherry-yl-sh** [scroll-tech/scroll-documentation#239]
### Describe the bug

a eth_call request  for simulate 
in ethereum or other op chain like optimism , arb, it work can return data
but in scroll not working

### To Reproduce

{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "from": "0x0000000000000000000000000000000000000000",
            "to": "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
            "data": "0xd6383f940000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004e0000000000000000000000000ffdb071c2b58ccc10ad386f9bb4e8d3d664ce73c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000054fa000000000000000000000000000000000000000000000000000000000005fa35000000000000000000000000000000000000000000000000000000000000ae64000000000000000000000000000000000000000000000000000000005968606e0000000000000000000000000000000000000000000000000000000059682f000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000589406cc6185a346906296840746125a0e449764545fbfb9cf000000000000000000000000b6bcf9517d193f551d0e3d6860103972dd13de7b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e4b61d27f60000000000000000000000001c7d4b196cb0c7b01d743fbc6116a902379c7238000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044095ea7b30000000000000000000000000000000000325602a77416a16136fdafd04b299fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d50fa9ee28202f8602e9a4c99af799c75c29afbc89000000000000000000000000000000000000000000000000000000006c7bacd00000000000000000000000000000000000000000000000000000000065ed35500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030834e50943434af33947ba6de358766961c7b89ae4b496a11d2b53771479e45220a8caa0024b81a2ed649b26a292c5f5b2870da090e3cc4490688a4874869721c00000000000000000000000000000000000000000000000000000000000000000000000000000000000041aa846693598194980f3bf50486be854704534c1622d0c2ee895a5a1ebe1508221909a27cc7971d9f522c8df13b9d8a6ee446d09ea7635f31c59d77d35d1281421c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        },
        "latest"
    ],
    "id": 1
}
here is the request 
request to Ethereum. sepolia 
![image](https://github.com/scroll-tech/scroll-documentation/assets/60910788/891f996d-2ecb-4019-a832-b1aa744ee9a2)

but call. scroll sepolia return errror 
![image](https://github.com/scroll-tech/scroll-documentation/assets/60910788/d131c2a7-4698-4386-ac25-eeeaaf2b9209)

### URLs

not link just rpc call error 

### Expected behavior

should return like ethereum call response ,it is  EVM compatible chain right ?

**Comment by Thegaram** [comment]
Please open an issue on https://github.com/scroll-tech/go-ethereum.
