### ISSUE TITLE
[Enhancement]: Add FAQs to Scroll docs

### ISSUE THREAD

**Issue by juve4ever** [scroll-tech/scroll-documentation#55]
### What would you like us to improve?

Adding some FAQs in Scroll docs 

### How important it is?

 They provide answers to common queries and help users find information quickly and easily. They serve as a valuable resource for users who may have similar questions or concerns. FAQs can save time for both users and support teams by addressing common issues upfront and reducing the need for repetitive inquiries.

**Comment by dghelm** [comment]
Thanks for the suggestion @juve4ever ! Is there a specific area you'd like to see FAQs about? Information about the protocol? About using the network? About developing on Scroll?

**Comment by juve4ever** [comment]
> Thanks for the suggestion @juve4ever ! Is there a specific area you'd like to see FAQs about? Information about the protocol? About using the network? About developing on Scroll?

i think in Scroll docs will be good place to insert FAQs. General FAQs like the one in your Discord.

**Comment by dghelm** [comment]
We'll take this into consideration, but for now I'll close it as we figure out the next iteration of our page hierarchy.
