### ISSUE TITLE
[Bug]: <Latest Blog Links Broke>

### ISSUE THREAD

**Issue by Junweif2** [scroll-tech/scroll-documentation#73]
### Describe the bug

https://scroll.io/blog/scrollsFreshCoat 
The blog link to developer portal is broke

### To Reproduce

**https://https//docs.scroll.io/en/home/** should be **https://docs.scroll.io/en/home/**

### URLs

https://scroll.io/blog/scrollsFreshCoat

**Comment by dghelm** [comment]
Thanks for the heads up -- fixed in the proper repo.
